<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByModelSorted(string $make)
    {
        return $this->createQueryBuilder('c')
            ->where('c.make = :make')
            ->setParameter('make', $make)
            ->orderBy('c.model', 'ASC')
            ->orderBy('c.traveledDistance', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getAllByMake()
    {
        return $this->createQueryBuilder('c')
            ->groupBy('c.make')
            ->getQuery()
            ->getResult();
    }

}
